### PR TITLE
Last diffs from my branch

### PR DESCRIPTION
**Pull request by vonloxley**
These are the last to changes I had in my fork. bc61e0e might need more work.

### CODE REVIEW

**Comment by MER-C** [comment]
Please provide a test case for bc61e0e , I'd like to fix the bug(s) in normalize() instead.

**Comment by vonloxley** [comment]
This might have been fixed by f0c7926. I’ll investigate a little further…

**Comment by vonloxley** [comment]
I removed the commit.

**Comment by MER-C** [comment]
Please also update the documentation.

**Comment by vonloxley** [comment]
Fix a possible recursion.

**Pull request merged**
