### PR TITLE
add Travis CI support

### PR DESCRIPTION
**Pull request by intracer**
Create .travis.yml / Add travis badge

### CODE REVIEW

**Comment by intracer** [comment]
Should resolve  #66

**Comment by MarcoFalke** [comment]
+1 We need a ci where the results of a build are publicly available.

**Comment by MarcoFalke** [comment]
@MER-C I think you still need to https://travis-ci.org/auth and then enable the MER-C/wiki-java project in travis.

**Comment by MER-C** [comment]
Done.

**Pull request merged**
